### ISSUE TITLE
FFF release checklist

### ISSUE THREAD

**Issue by wanderingstan** [error-central/diffenv#21]
# Dev
- [x] Remove Port Facet - @wanderingstan 
- [x] Remove file facet - @wanderingstan 
- [x] Diagnose problem with missing command stderr not getting output (e.g. `composer`) - gabe/stan
- [x] Remove color from diff output when using `--output` flag - @werg 
- [x] diffenv version (pip vs pip3) - ???

# Docs
- [x] Better example env in repo (current one is from long ago and broken)
- [ ] Another pass at the readme
- [ ] (Maybe?) compose email for FFF's, or at least talking poins
- [x]  push to pip and test
- [ ] issue template use diffenv
